import type { PlatformSettings } from '../types/admin';

const SETTINGS_KEY = 'pdfdecor_platform_settings';

export const DEFAULT_SETTINGS: PlatformSettings = {
  siteName: 'PDFDecor',
  siteUrl: 'https://pdfdecor.in',
  freePlanDailyLimit: 5,
  watermarkText: 'Generated by PDFDecor.in',
  monthlyPrice: 249,
  yearlyPrice: 2390,
  adsEnabled: true,
  adHomepageBanner: true,
  adGeneratorSidebar: true,
  adFooter: true,
  maintenanceMode: false,
};

export function getSettings(): PlatformSettings {
  try {
    const stored = JSON.parse(localStorage.getItem(SETTINGS_KEY) || '{}');
    return { ...DEFAULT_SETTINGS, ...stored };
  } catch { return { ...DEFAULT_SETTINGS }; }
}

export function saveSettings(settings: PlatformSettings): void {
  localStorage.setItem(SETTINGS_KEY, JSON.stringify(settings));
}
