import { useEffect, useState } from 'react';
import QRCode from 'qrcode';

export interface EventPassData {
  eventName: string;
  eventDate: string;
  eventTime: string;
  eventVenue: string;
  passHolder: string;
  passType: string; // VIP, General, Media, etc.
  passNumber: string;
  organizerName: string;
  organizerContact?: string;
  logo?: string;
  description?: string;
  validFor?: string;
}

interface Props { data: EventPassData; isPro?: boolean; }

const PASS_STYLE: React.CSSProperties = {
  width: '400px', borderRadius: '16px', position: 'relative',
  fontFamily: 'system-ui, sans-serif', overflow: 'hidden',
};

export function EventPassTemplate1({ data, isPro = false }: Props) {
  const [qr, setQr] = useState('');
  useEffect(() => {
    const qrText = `PASS:${data.passNumber}|${data.eventName}|${data.passHolder}|${data.passType}`;
    QRCode.toDataURL(qrText, { width: 80, margin: 1 }).then(setQr).catch(console.error);
  }, [data]);

  return (
    <div style={{ backgroundColor: '#fff', padding: '40px', maxWidth: '800px', margin: '0 auto', minHeight: '600px' }}>
      {!isPro && <p style={{ textAlign: 'center', fontSize: '11px', color: '#9ca3af', marginBottom: '12px' }}>Generated by PDFDecor.in (Free)</p>}
      <div style={{ display: 'flex', justifyContent: 'center' }}>
        <div style={{ ...PASS_STYLE }}>
          {/* Header */}
          <div style={{ background: 'linear-gradient(135deg, #7c3aed, #4f46e5)', padding: '24px', color: '#fff' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
              <div style={{ flex: 1 }}>
                <p style={{ fontSize: '9px', textTransform: 'uppercase', letterSpacing: '3px', opacity: 0.7, margin: '0 0 6px' }}>Event Pass</p>
                <h2 style={{ fontSize: '22px', fontWeight: '900', margin: '0 0 8px', lineHeight: '1.2' }}>{data.eventName}</h2>
                <p style={{ fontSize: '12px', opacity: 0.85, margin: 0 }}>📅 {data.eventDate} · {data.eventTime}</p>
                <p style={{ fontSize: '12px', opacity: 0.75, margin: '4px 0 0' }}>📍 {data.eventVenue}</p>
              </div>
              <span style={{ background: 'rgba(255,255,255,0.2)', color: '#fff', padding: '6px 14px', borderRadius: '20px', fontSize: '11px', fontWeight: '900', flexShrink: 0, marginLeft: '12px', border: '1px solid rgba(255,255,255,0.3)' }}>
                {data.passType.toUpperCase()}
              </span>
            </div>
          </div>
          {/* Dashed separator */}
          <div style={{ display: 'flex', alignItems: 'center', background: '#f5f3ff' }}>
            <div style={{ width: '20px', height: '20px', borderRadius: '50%', background: '#fff', marginLeft: '-10px', flexShrink: 0 }}></div>
            <div style={{ flex: 1, borderTop: '2px dashed #c4b5fd', margin: '0 4px' }}></div>
            <div style={{ width: '20px', height: '20px', borderRadius: '50%', background: '#fff', marginRight: '-10px', flexShrink: 0 }}></div>
          </div>
          {/* Body */}
          <div style={{ background: '#f5f3ff', padding: '20px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <div>
                <p style={{ fontSize: '9px', color: '#7c3aed', textTransform: 'uppercase', letterSpacing: '1px', margin: '0 0 4px' }}>Pass Holder</p>
                <p style={{ fontWeight: '900', color: '#1f2937', fontSize: '18px', margin: '0 0 4px' }}>{data.passHolder}</p>
                <p style={{ fontSize: '11px', color: '#6b7280', margin: '0 0 2px' }}>Organizer: {data.organizerName}</p>
                {data.organizerContact && <p style={{ fontSize: '11px', color: '#6b7280', margin: 0 }}>Contact: {data.organizerContact}</p>}
                <p style={{ fontSize: '11px', color: '#7c3aed', fontWeight: '600', margin: '8px 0 0' }}>Pass #: {data.passNumber}</p>
              </div>
              <div style={{ textAlign: 'center' }}>
                {qr && <img src={qr} alt="QR" style={{ width: '70px', height: '70px', background: '#fff', padding: '4px', borderRadius: '8px', boxShadow: '0 2px 8px rgba(0,0,0,0.1)' }} />}
                <p style={{ fontSize: '8px', color: '#9ca3af', margin: '4px 0 0' }}>Scan to verify</p>
              </div>
            </div>
            {data.description && <p style={{ fontSize: '10px', color: '#6b7280', marginTop: '12px', paddingTop: '12px', borderTop: '1px solid #e9d5ff' }}>{data.description}</p>}
          </div>
        </div>
      </div>
    </div>
  );
}

export function EventPassTemplate2({ data, isPro = false }: Props) {
  const [qr, setQr] = useState('');
  useEffect(() => {
    QRCode.toDataURL(`PASS:${data.passNumber}|${data.passHolder}`, { width: 80, margin: 1 }).then(setQr).catch(console.error);
  }, [data]);
  return (
    <div style={{ backgroundColor: '#fff', padding: '40px', maxWidth: '800px', margin: '0 auto', minHeight: '600px' }}>
      {!isPro && <p style={{ textAlign: 'center', fontSize: '11px', color: '#9ca3af', marginBottom: '12px' }}>Generated by PDFDecor.in (Free)</p>}
      <div style={{ display: 'flex', justifyContent: 'center' }}>
        <div style={{ ...PASS_STYLE, background: '#0f172a', color: '#e2e8f0', border: '1px solid #1e293b' }}>
          <div style={{ background: 'linear-gradient(90deg, #0ea5e9, #38bdf8)', height: '6px' }}></div>
          <div style={{ padding: '24px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '16px' }}>
              <div>
                <p style={{ fontSize: '9px', color: '#38bdf8', textTransform: 'uppercase', letterSpacing: '3px', margin: '0 0 8px' }}>Event Pass</p>
                <h2 style={{ fontSize: '20px', fontWeight: '900', color: '#f1f5f9', margin: '0 0 6px', lineHeight: '1.2' }}>{data.eventName}</h2>
                <p style={{ fontSize: '11px', color: '#94a3b8', margin: '0 0 3px' }}>{data.eventDate} | {data.eventTime}</p>
                <p style={{ fontSize: '11px', color: '#94a3b8', margin: 0 }}>{data.eventVenue}</p>
              </div>
              <span style={{ background: '#0ea5e9', color: '#fff', padding: '5px 12px', borderRadius: '20px', fontSize: '10px', fontWeight: '900', flexShrink: 0 }}>{data.passType}</span>
            </div>
            <div style={{ borderTop: '1px dashed #334155', margin: '16px 0' }}></div>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <div>
                <p style={{ fontSize: '9px', color: '#64748b', textTransform: 'uppercase', letterSpacing: '1px', margin: '0 0 4px' }}>Attendee</p>
                <p style={{ fontSize: '17px', fontWeight: '900', color: '#f1f5f9', margin: '0 0 4px' }}>{data.passHolder}</p>
                <p style={{ fontSize: '10px', color: '#94a3b8', margin: '0 0 2px' }}>{data.organizerName}</p>
                <p style={{ fontSize: '10px', color: '#38bdf8', fontWeight: '600', margin: 0 }}>#{data.passNumber}</p>
              </div>
              {qr && <img src={qr} alt="QR" style={{ width: '65px', height: '65px', background: '#fff', padding: '4px', borderRadius: '6px' }} />}
            </div>
            {data.description && <p style={{ fontSize: '9px', color: '#64748b', marginTop: '14px', paddingTop: '12px', borderTop: '1px solid #1e293b' }}>{data.description}</p>}
          </div>
        </div>
      </div>
    </div>
  );
}

export function EventPassTemplate3({ data, isPro = false }: Props) {
  const [qr, setQr] = useState('');
  useEffect(() => {
    QRCode.toDataURL(`PASS:${data.passNumber}|${data.passHolder}`, { width: 80, margin: 1 }).then(setQr).catch(console.error);
  }, [data]);
  return (
    <div style={{ backgroundColor: '#fff', padding: '40px', maxWidth: '800px', margin: '0 auto', minHeight: '600px' }}>
      {!isPro && <p style={{ textAlign: 'center', fontSize: '11px', color: '#9ca3af', marginBottom: '12px' }}>Generated by PDFDecor.in (Free)</p>}
      <div style={{ display: 'flex', justifyContent: 'center' }}>
        <div style={{ ...PASS_STYLE, background: 'linear-gradient(135deg, #f59e0b, #ef4444)', color: '#fff' }}>
          <div style={{ padding: '24px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '16px' }}>
              <div>
                <p style={{ fontSize: '9px', textTransform: 'uppercase', letterSpacing: '3px', opacity: 0.75, margin: '0 0 8px' }}>🎫 Event Pass</p>
                <h2 style={{ fontSize: '22px', fontWeight: '900', margin: '0 0 6px', lineHeight: '1.2' }}>{data.eventName}</h2>
                <p style={{ fontSize: '11px', opacity: 0.85, margin: '0 0 3px' }}>{data.eventDate} · {data.eventTime}</p>
                <p style={{ fontSize: '11px', opacity: 0.7, margin: 0 }}>📍 {data.eventVenue}</p>
              </div>
              <div style={{ textAlign: 'center', flexShrink: 0, marginLeft: '12px' }}>
                {qr && <img src={qr} alt="QR" style={{ width: '64px', height: '64px', background: '#fff', padding: '4px', borderRadius: '8px' }} />}
                <p style={{ fontSize: '7px', opacity: 0.7, margin: '4px 0 0' }}>Scan to verify</p>
              </div>
            </div>
            <div style={{ background: 'rgba(0,0,0,0.2)', borderRadius: '12px', padding: '14px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <div>
                <p style={{ fontSize: '9px', opacity: 0.7, textTransform: 'uppercase', letterSpacing: '1px', margin: '0 0 4px' }}>Pass Holder</p>
                <p style={{ fontSize: '18px', fontWeight: '900', margin: '0 0 4px' }}>{data.passHolder}</p>
                <p style={{ fontSize: '10px', opacity: 0.8, margin: 0 }}>By: {data.organizerName}</p>
              </div>
              <div style={{ textAlign: 'right' }}>
                <span style={{ background: 'rgba(255,255,255,0.25)', padding: '4px 12px', borderRadius: '20px', fontSize: '10px', fontWeight: '900', display: 'block', marginBottom: '4px' }}>{data.passType.toUpperCase()}</span>
                <p style={{ fontSize: '10px', opacity: 0.8, margin: 0 }}>#{data.passNumber}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// Template 4 - Pro: Corporate
export function EventPassTemplate4({ data, isPro = false }: Props) {
  const [qr, setQr] = useState('');
  useEffect(() => {
    QRCode.toDataURL(`PASS:${data.passNumber}|${data.passHolder}`, { width: 80, margin: 1 }).then(setQr).catch(console.error);
  }, [data]);
  return (
    <div style={{ backgroundColor: '#fff', padding: '40px', maxWidth: '800px', margin: '0 auto', minHeight: '600px' }}>
      <div style={{ display: 'flex', justifyContent: 'center' }}>
        <div style={{ ...PASS_STYLE, background: '#fff', border: '2px solid #e5e7eb', boxShadow: '0 8px 32px rgba(0,0,0,0.1)' }}>
          <div style={{ background: '#166534', padding: '20px', color: '#fff', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <div>
              <h2 style={{ fontSize: '20px', fontWeight: '900', margin: '0 0 4px' }}>{data.eventName}</h2>
              <p style={{ fontSize: '11px', opacity: 0.8, margin: 0 }}>{data.eventDate} | {data.eventTime}</p>
            </div>
            <span style={{ background: '#d1fae5', color: '#166534', padding: '5px 12px', borderRadius: '20px', fontSize: '10px', fontWeight: '900' }}>{data.passType}</span>
          </div>
          <div style={{ padding: '20px' }}>
            <p style={{ fontSize: '11px', color: '#6b7280', margin: '0 0 4px' }}>📍 {data.eventVenue}</p>
            <div style={{ borderTop: '1px dashed #d1d5db', margin: '14px 0' }}></div>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <div>
                <p style={{ fontSize: '9px', color: '#16a34a', textTransform: 'uppercase', letterSpacing: '1px', margin: '0 0 4px' }}>Attendee</p>
                <p style={{ fontSize: '17px', fontWeight: '900', color: '#1f2937', margin: '0 0 4px' }}>{data.passHolder}</p>
                <p style={{ fontSize: '10px', color: '#6b7280', margin: 0 }}>{data.organizerName}</p>
                <p style={{ fontSize: '10px', color: '#166534', fontWeight: '600', margin: '4px 0 0' }}>#{data.passNumber}</p>
              </div>
              {qr && <img src={qr} alt="QR" style={{ width: '65px', height: '65px' }} />}
            </div>
            {data.description && <p style={{ fontSize: '9px', color: '#6b7280', marginTop: '12px', paddingTop: '12px', borderTop: '1px solid #f3f4f6' }}>{data.description}</p>}
          </div>
        </div>
      </div>
    </div>
  );
}

// Template 5 - Pro: Neon Festival
export function EventPassTemplate5({ data, isPro = false }: Props) {
  const [qr, setQr] = useState('');
  useEffect(() => {
    QRCode.toDataURL(`PASS:${data.passNumber}|${data.passHolder}`, { width: 80, margin: 1 }).then(setQr).catch(console.error);
  }, [data]);
  return (
    <div style={{ backgroundColor: '#fff', padding: '40px', maxWidth: '800px', margin: '0 auto', minHeight: '600px' }}>
      <div style={{ display: 'flex', justifyContent: 'center' }}>
        <div style={{ ...PASS_STYLE, background: '#000', color: '#fff', border: '1px solid #333' }}>
          <div style={{ background: 'linear-gradient(90deg, #ff00aa, #aa00ff, #00aaff)', height: '4px' }}></div>
          <div style={{ padding: '24px' }}>
            <div style={{ marginBottom: '16px' }}>
              <p style={{ fontSize: '8px', color: '#aaa', textTransform: 'uppercase', letterSpacing: '4px', margin: '0 0 8px' }}>🎪 Event Pass</p>
              <h2 style={{ fontSize: '24px', fontWeight: '900', margin: '0 0 6px', background: 'linear-gradient(90deg, #ff00aa, #aa00ff)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>{data.eventName}</h2>
              <p style={{ fontSize: '11px', color: '#aaa', margin: '0 0 2px' }}>{data.eventDate} · {data.eventTime}</p>
              <p style={{ fontSize: '11px', color: '#aaa', margin: 0 }}>{data.eventVenue}</p>
            </div>
            <div style={{ border: '1px dashed #333', margin: '16px 0' }}></div>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <div>
                <p style={{ fontSize: '8px', color: '#888', textTransform: 'uppercase', letterSpacing: '2px', margin: '0 0 4px' }}>Attendee</p>
                <p style={{ fontSize: '18px', fontWeight: '900', margin: '0 0 4px' }}>{data.passHolder}</p>
                <p style={{ fontSize: '10px', color: '#888', margin: '0 0 4px' }}>By {data.organizerName}</p>
                <span style={{ background: 'linear-gradient(90deg, #ff00aa, #aa00ff)', color: '#fff', padding: '3px 10px', borderRadius: '10px', fontSize: '9px', fontWeight: '900' }}>{data.passType}</span>
              </div>
              <div style={{ textAlign: 'center' }}>
                {qr && <img src={qr} alt="QR" style={{ width: '64px', height: '64px', background: '#fff', padding: '4px', borderRadius: '6px' }} />}
                <p style={{ fontSize: '8px', color: '#555', margin: '4px 0 0' }}>#{data.passNumber}</p>
              </div>
            </div>
          </div>
          <div style={{ background: 'linear-gradient(90deg, #ff00aa, #aa00ff, #00aaff)', height: '4px' }}></div>
        </div>
      </div>
    </div>
  );
}
