import { useEffect, useState } from 'react';
import QRCode from 'qrcode';

export interface IDCardData {
  name: string;
  designation: string;
  department: string;
  employeeId: string;
  organization: string;
  orgAddress?: string;
  orgPhone?: string;
  orgEmail?: string;
  bloodGroup?: string;
  dob?: string;
  validUntil?: string;
  photo?: string; // base64 or URL
  logo?: string;
  qrData?: string;
}

interface Props { data: IDCardData; isPro?: boolean; }

const CARD_STYLE: React.CSSProperties = {
  width: '340px', height: '210px', borderRadius: '12px', position: 'relative', overflow: 'hidden',
  fontFamily: 'system-ui, sans-serif', display: 'inline-block', pageBreakInside: 'avoid',
};

export function IDCardTemplate1({ data, isPro = false }: Props) {
  const [qr, setQr] = useState('');
  useEffect(() => {
    const qrText = data.qrData || `ID:${data.employeeId}|${data.name}|${data.organization}`;
    QRCode.toDataURL(qrText, { width: 60, margin: 1 }).then(setQr).catch(console.error);
  }, [data]);

  return (
    <div style={{ backgroundColor: '#fff', padding: '40px', maxWidth: '800px', margin: '0 auto', minHeight: '600px', fontFamily: 'system-ui, sans-serif' }}>
      {!isPro && <p style={{ textAlign: 'center', fontSize: '11px', color: '#9ca3af', marginBottom: '12px' }}>Generated by PDFDecor.in (Free)</p>}
      <div style={{ display: 'flex', justifyContent: 'center', gap: '24px', flexWrap: 'wrap' }}>
        {/* Front */}
        <div>
          <p style={{ textAlign: 'center', fontSize: '11px', color: '#6b7280', marginBottom: '8px' }}>— FRONT —</p>
          <div style={{ ...CARD_STYLE, background: 'linear-gradient(135deg, #1e40af, #3b82f6)' }}>
            <div style={{ position: 'absolute', top: 0, right: 0, width: '120px', height: '120px', background: 'rgba(255,255,255,0.05)', borderRadius: '50%', transform: 'translate(40px, -40px)' }}></div>
            <div style={{ padding: '16px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '12px' }}>
                <div>
                  {data.logo ? <img src={data.logo} alt="logo" style={{ height: '28px', maxWidth: '60px', objectFit: 'contain' }} /> : <div style={{ fontSize: '13px', fontWeight: '900', color: '#fff' }}>{data.organization.slice(0, 12)}</div>}
                  <p style={{ fontSize: '8px', color: 'rgba(255,255,255,0.7)', margin: '2px 0 0', textTransform: 'uppercase', letterSpacing: '1px' }}>EMPLOYEE ID CARD</p>
                </div>
                <div style={{ width: '52px', height: '64px', background: '#fff', borderRadius: '6px', display: 'flex', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' }}>
                  {data.photo ? <img src={data.photo} alt="photo" style={{ width: '100%', height: '100%', objectFit: 'cover' }} /> : <div style={{ fontSize: '20px', color: '#93c5fd' }}>👤</div>}
                </div>
              </div>
              <p style={{ fontSize: '16px', fontWeight: '900', color: '#fff', margin: '0 0 2px' }}>{data.name}</p>
              <p style={{ fontSize: '11px', color: '#bfdbfe', margin: '0 0 2px' }}>{data.designation}</p>
              <p style={{ fontSize: '10px', color: 'rgba(255,255,255,0.6)', margin: 0 }}>{data.department}</p>
              <div style={{ position: 'absolute', bottom: '12px', left: '16px', right: '16px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <div>
                  <p style={{ fontSize: '8px', color: 'rgba(255,255,255,0.5)', margin: '0 0 2px', textTransform: 'uppercase' }}>ID Number</p>
                  <p style={{ fontSize: '11px', color: '#93c5fd', fontWeight: 'bold', margin: 0 }}>{data.employeeId}</p>
                </div>
                {data.validUntil && <p style={{ fontSize: '8px', color: 'rgba(255,255,255,0.5)' }}>Valid: {data.validUntil}</p>}
              </div>
            </div>
          </div>
        </div>
        {/* Back */}
        <div>
          <p style={{ textAlign: 'center', fontSize: '11px', color: '#6b7280', marginBottom: '8px' }}>— BACK —</p>
          <div style={{ ...CARD_STYLE, background: '#1e3a8a' }}>
            <div style={{ padding: '16px' }}>
              <p style={{ fontSize: '10px', fontWeight: '900', color: '#93c5fd', textTransform: 'uppercase', letterSpacing: '1px', margin: '0 0 10px' }}>{data.organization}</p>
              <div style={{ display: 'flex', gap: '12px', alignItems: 'flex-start' }}>
                {qr && <img src={qr} alt="QR" style={{ width: '56px', height: '56px', background: '#fff', padding: '4px', borderRadius: '4px' }} />}
                <div style={{ fontSize: '10px', color: 'rgba(255,255,255,0.75)', lineHeight: '1.6' }}>
                  {data.orgAddress && <p style={{ margin: '0 0 3px' }}>{data.orgAddress}</p>}
                  {data.orgPhone && <p style={{ margin: '0 0 3px' }}>📞 {data.orgPhone}</p>}
                  {data.orgEmail && <p style={{ margin: '0 0 3px' }}>✉ {data.orgEmail}</p>}
                </div>
              </div>
              <div style={{ position: 'absolute', bottom: '12px', left: '16px', right: '16px' }}>
                {data.bloodGroup && <span style={{ background: '#ef4444', color: '#fff', fontSize: '9px', fontWeight: 'bold', padding: '2px 8px', borderRadius: '10px' }}>🩸 {data.bloodGroup}</span>}
                <p style={{ fontSize: '8px', color: 'rgba(255,255,255,0.4)', margin: '6px 0 0' }}>If found, please return to the above address.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export function IDCardTemplate2({ data, isPro = false }: Props) {
  const [qr, setQr] = useState('');
  useEffect(() => {
    const qrText = data.qrData || `ID:${data.employeeId}|${data.name}|${data.organization}`;
    QRCode.toDataURL(qrText, { width: 60, margin: 1 }).then(setQr).catch(console.error);
  }, [data]);
  return (
    <div style={{ backgroundColor: '#fff', padding: '40px', maxWidth: '800px', margin: '0 auto', minHeight: '600px' }}>
      {!isPro && <p style={{ textAlign: 'center', fontSize: '11px', color: '#9ca3af', marginBottom: '12px' }}>Generated by PDFDecor.in (Free)</p>}
      <div style={{ display: 'flex', justifyContent: 'center', gap: '24px', flexWrap: 'wrap' }}>
        <div>
          <p style={{ textAlign: 'center', fontSize: '11px', color: '#6b7280', marginBottom: '8px' }}>— FRONT —</p>
          <div style={{ ...CARD_STYLE, background: '#fff', border: '2px solid #e5e7eb', boxShadow: '0 4px 20px rgba(0,0,0,0.1)' }}>
            <div style={{ height: '6px', background: 'linear-gradient(90deg, #10b981, #059669)', position: 'absolute', top: 0, left: 0, right: 0 }}></div>
            <div style={{ padding: '18px 16px 12px' }}>
              <div style={{ display: 'flex', gap: '12px', alignItems: 'flex-start' }}>
                <div style={{ width: '56px', height: '70px', background: '#d1fae5', borderRadius: '8px', overflow: 'hidden', flexShrink: 0, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  {data.photo ? <img src={data.photo} alt="photo" style={{ width: '100%', height: '100%', objectFit: 'cover' }} /> : <span style={{ fontSize: '24px' }}>👤</span>}
                </div>
                <div style={{ flex: 1 }}>
                  <p style={{ fontSize: '13px', fontWeight: '900', color: '#1f2937', margin: '0 0 2px' }}>{data.name}</p>
                  <p style={{ fontSize: '10px', color: '#059669', fontWeight: '600', margin: '0 0 2px' }}>{data.designation}</p>
                  <p style={{ fontSize: '9px', color: '#6b7280', margin: 0 }}>{data.department}</p>
                  <p style={{ fontSize: '10px', fontWeight: 'bold', color: '#374151', margin: '8px 0 0' }}>{data.organization}</p>
                </div>
              </div>
              <div style={{ position: 'absolute', bottom: '12px', left: '16px', right: '16px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <div style={{ background: '#f0fdf4', padding: '4px 10px', borderRadius: '8px', border: '1px solid #bbf7d0' }}>
                  <p style={{ fontSize: '8px', color: '#6b7280', margin: 0 }}>ID</p>
                  <p style={{ fontSize: '11px', fontWeight: 'bold', color: '#059669', margin: 0 }}>{data.employeeId}</p>
                </div>
                {data.bloodGroup && <span style={{ fontSize: '9px', color: '#dc2626', fontWeight: 'bold', background: '#fee2e2', padding: '2px 8px', borderRadius: '10px' }}>{data.bloodGroup}</span>}
                {data.validUntil && <p style={{ fontSize: '8px', color: '#9ca3af' }}>Valid: {data.validUntil}</p>}
              </div>
            </div>
          </div>
        </div>
        <div>
          <p style={{ textAlign: 'center', fontSize: '11px', color: '#6b7280', marginBottom: '8px' }}>— BACK —</p>
          <div style={{ ...CARD_STYLE, background: '#fff', border: '2px solid #e5e7eb' }}>
            <div style={{ height: '6px', background: 'linear-gradient(90deg, #10b981, #059669)', position: 'absolute', top: 0, left: 0, right: 0 }}></div>
            <div style={{ padding: '18px 16px' }}>
              <p style={{ fontSize: '10px', fontWeight: '900', color: '#059669', textTransform: 'uppercase', letterSpacing: '1px', margin: '0 0 10px' }}>{data.organization}</p>
              <div style={{ display: 'flex', gap: '12px' }}>
                {qr && <img src={qr} alt="QR" style={{ width: '52px', height: '52px' }} />}
                <div style={{ fontSize: '9px', color: '#6b7280', lineHeight: '1.7' }}>
                  {data.orgAddress && <p style={{ margin: '0 0 2px' }}>{data.orgAddress}</p>}
                  {data.orgPhone && <p style={{ margin: '0 0 2px' }}>{data.orgPhone}</p>}
                  {data.orgEmail && <p style={{ margin: 0 }}>{data.orgEmail}</p>}
                </div>
              </div>
              <p style={{ position: 'absolute', bottom: '12px', left: '16px', fontSize: '7px', color: '#d1d5db' }}>If found, please return to above address.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export function IDCardTemplate3({ data, isPro = false }: Props) {
  return (
    <div style={{ backgroundColor: '#fff', padding: '40px', maxWidth: '800px', margin: '0 auto', minHeight: '600px' }}>
      {!isPro && <p style={{ textAlign: 'center', fontSize: '11px', color: '#9ca3af', marginBottom: '12px' }}>Generated by PDFDecor.in (Free)</p>}
      <div style={{ display: 'flex', justifyContent: 'center', gap: '24px', flexWrap: 'wrap' }}>
        <div>
          <p style={{ textAlign: 'center', fontSize: '11px', color: '#6b7280', marginBottom: '8px' }}>— FRONT —</p>
          <div style={{ ...CARD_STYLE, background: 'linear-gradient(135deg, #7c3aed, #a855f7)' }}>
            <div style={{ position: 'absolute', bottom: -20, right: -20, width: '100px', height: '100px', background: 'rgba(255,255,255,0.07)', borderRadius: '50%' }}></div>
            <div style={{ padding: '14px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
                <p style={{ fontSize: '9px', color: 'rgba(255,255,255,0.7)', textTransform: 'uppercase', letterSpacing: '2px', margin: 0 }}>ID CARD</p>
                {data.logo ? <img src={data.logo} alt="logo" style={{ height: '22px' }} /> : <p style={{ fontSize: '9px', color: '#e9d5ff', fontWeight: 'bold', margin: 0 }}>{data.organization.slice(0, 10)}</p>}
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                <div style={{ width: '58px', height: '72px', borderRadius: '8px', overflow: 'hidden', border: '2px solid rgba(255,255,255,0.4)', background: '#8b5cf6', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                  {data.photo ? <img src={data.photo} alt="photo" style={{ width: '100%', height: '100%', objectFit: 'cover' }} /> : <span style={{ fontSize: '24px' }}>👤</span>}
                </div>
                <div>
                  <p style={{ fontWeight: '900', color: '#fff', fontSize: '14px', margin: '0 0 3px' }}>{data.name}</p>
                  <p style={{ color: '#e9d5ff', fontSize: '10px', margin: '0 0 2px' }}>{data.designation}</p>
                  <p style={{ color: 'rgba(255,255,255,0.6)', fontSize: '9px', margin: 0 }}>{data.department}</p>
                </div>
              </div>
              <div style={{ position: 'absolute', bottom: '10px', left: '14px', right: '14px', display: 'flex', justifyContent: 'space-between' }}>
                <p style={{ fontSize: '9px', color: '#c4b5fd', fontWeight: 'bold', margin: 0 }}>{data.employeeId}</p>
                {data.bloodGroup && <span style={{ fontSize: '8px', background: '#7f1d1d', color: '#fca5a5', padding: '1px 6px', borderRadius: '8px' }}>{data.bloodGroup}</span>}
              </div>
            </div>
          </div>
        </div>
        <div>
          <p style={{ textAlign: 'center', fontSize: '11px', color: '#6b7280', marginBottom: '8px' }}>— BACK —</p>
          <div style={{ ...CARD_STYLE, background: '#f5f3ff', border: '2px solid #e9d5ff' }}>
            <div style={{ padding: '16px' }}>
              <p style={{ fontWeight: '900', color: '#7c3aed', fontSize: '11px', margin: '0 0 8px', textTransform: 'uppercase', letterSpacing: '1px' }}>{data.organization}</p>
              <div style={{ fontSize: '9px', color: '#6b7280', lineHeight: '1.7', marginBottom: '8px' }}>
                {data.orgAddress && <p style={{ margin: '0 0 2px' }}>{data.orgAddress}</p>}
                {data.orgPhone && <p style={{ margin: '0 0 2px' }}>{data.orgPhone}</p>}
                {data.orgEmail && <p style={{ margin: 0 }}>{data.orgEmail}</p>}
              </div>
              {data.validUntil && <p style={{ fontSize: '9px', color: '#7c3aed', fontWeight: '600' }}>Valid until: {data.validUntil}</p>}
              <p style={{ position: 'absolute', bottom: '10px', left: '16px', fontSize: '7px', color: '#c4b5fd' }}>Scan QR for verification</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// Template 4 - Pro: Corporate Minimal
export function IDCardTemplate4({ data, isPro = false }: Props) {
  return (
    <div style={{ backgroundColor: '#fff', padding: '40px', maxWidth: '800px', margin: '0 auto', minHeight: '600px' }}>
      <div style={{ display: 'flex', justifyContent: 'center', gap: '24px', flexWrap: 'wrap' }}>
        <div>
          <p style={{ textAlign: 'center', fontSize: '11px', color: '#6b7280', marginBottom: '8px' }}>— FRONT —</p>
          <div style={{ ...CARD_STYLE, background: '#0f172a', border: '1px solid #1e293b' }}>
            <div style={{ padding: '14px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '10px' }}>
                <p style={{ fontSize: '8px', color: '#38bdf8', textTransform: 'uppercase', letterSpacing: '2px', margin: 0 }}>Employee Card</p>
                {data.logo ? <img src={data.logo} alt="logo" style={{ height: '20px' }} /> : <p style={{ fontSize: '9px', color: '#38bdf8', fontWeight: 'bold', margin: 0 }}>{data.organization.slice(0, 8)}</p>}
              </div>
              <div style={{ display: 'flex', gap: '10px', alignItems: 'center' }}>
                <div style={{ width: '52px', height: '64px', borderRadius: '6px', background: '#1e293b', overflow: 'hidden', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  {data.photo ? <img src={data.photo} alt="photo" style={{ width: '100%', height: '100%', objectFit: 'cover' }} /> : <span style={{ fontSize: '22px' }}>👤</span>}
                </div>
                <div>
                  <p style={{ fontWeight: 'bold', color: '#f1f5f9', fontSize: '13px', margin: '0 0 2px' }}>{data.name}</p>
                  <p style={{ color: '#38bdf8', fontSize: '10px', margin: '0 0 2px' }}>{data.designation}</p>
                  <p style={{ color: '#64748b', fontSize: '9px', margin: 0 }}>{data.department}</p>
                </div>
              </div>
              <div style={{ position: 'absolute', bottom: '10px', left: '14px', right: '14px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <p style={{ fontSize: '9px', color: '#94a3b8', margin: 0 }}>{data.employeeId}</p>
                {data.bloodGroup && <span style={{ fontSize: '8px', color: '#f87171', fontWeight: 'bold' }}>⬤ {data.bloodGroup}</span>}
              </div>
            </div>
          </div>
        </div>
        <div>
          <p style={{ textAlign: 'center', fontSize: '11px', color: '#6b7280', marginBottom: '8px' }}>— BACK —</p>
          <div style={{ ...CARD_STYLE, background: '#0f172a', border: '1px solid #1e293b' }}>
            <div style={{ padding: '14px' }}>
              <p style={{ fontSize: '10px', fontWeight: 'bold', color: '#38bdf8', margin: '0 0 8px' }}>{data.organization}</p>
              <div style={{ fontSize: '9px', color: '#64748b', lineHeight: '1.7' }}>
                {data.orgAddress && <p style={{ margin: '0 0 2px', color: '#94a3b8' }}>{data.orgAddress}</p>}
                {data.orgPhone && <p style={{ margin: '0 0 2px', color: '#94a3b8' }}>{data.orgPhone}</p>}
                {data.orgEmail && <p style={{ margin: 0, color: '#94a3b8' }}>{data.orgEmail}</p>}
              </div>
              {data.validUntil && <p style={{ fontSize: '9px', color: '#38bdf8', marginTop: '8px' }}>Valid: {data.validUntil}</p>}
              <p style={{ position: 'absolute', bottom: '10px', left: '14px', right: '14px', fontSize: '7px', color: '#334155', margin: 0 }}>If found, please return to the organization.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// Template 5 - Pro: Colorful Event
export function IDCardTemplate5({ data, isPro = false }: Props) {
  return (
    <div style={{ backgroundColor: '#fff', padding: '40px', maxWidth: '800px', margin: '0 auto', minHeight: '600px' }}>
      <div style={{ display: 'flex', justifyContent: 'center', gap: '24px', flexWrap: 'wrap' }}>
        <div>
          <p style={{ textAlign: 'center', fontSize: '11px', color: '#6b7280', marginBottom: '8px' }}>— FRONT —</p>
          <div style={{ ...CARD_STYLE, background: 'linear-gradient(135deg, #f97316, #ef4444)' }}>
            <div style={{ padding: '14px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px' }}>
                <p style={{ fontSize: '8px', color: 'rgba(255,255,255,0.8)', textTransform: 'uppercase', letterSpacing: '2px', margin: 0 }}>Staff ID</p>
                <p style={{ fontSize: '9px', color: '#fff', fontWeight: '900', margin: 0 }}>{data.organization.slice(0, 12)}</p>
              </div>
              <div style={{ display: 'flex', gap: '10px' }}>
                <div style={{ width: '54px', height: '68px', borderRadius: '8px', border: '3px solid rgba(255,255,255,0.6)', overflow: 'hidden', background: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  {data.photo ? <img src={data.photo} alt="photo" style={{ width: '100%', height: '100%', objectFit: 'cover' }} /> : <span style={{ fontSize: '24px' }}>👤</span>}
                </div>
                <div>
                  <p style={{ fontWeight: '900', color: '#fff', fontSize: '14px', margin: '0 0 2px' }}>{data.name}</p>
                  <p style={{ color: 'rgba(255,255,255,0.85)', fontSize: '10px', margin: '0 0 2px' }}>{data.designation}</p>
                  <p style={{ color: 'rgba(255,255,255,0.6)', fontSize: '9px', margin: 0 }}>{data.department}</p>
                </div>
              </div>
              <div style={{ position: 'absolute', bottom: '10px', left: '14px', right: '14px', display: 'flex', justifyContent: 'space-between' }}>
                <span style={{ background: 'rgba(255,255,255,0.2)', color: '#fff', fontSize: '9px', padding: '2px 8px', borderRadius: '8px', fontWeight: 'bold' }}>{data.employeeId}</span>
                {data.bloodGroup && <span style={{ background: '#7f1d1d', color: '#fca5a5', fontSize: '8px', padding: '2px 6px', borderRadius: '8px' }}>{data.bloodGroup}</span>}
              </div>
            </div>
          </div>
        </div>
        <div>
          <p style={{ textAlign: 'center', fontSize: '11px', color: '#6b7280', marginBottom: '8px' }}>— BACK —</p>
          <div style={{ ...CARD_STYLE, background: '#fff7ed', border: '2px solid #fed7aa' }}>
            <div style={{ padding: '14px' }}>
              <p style={{ fontWeight: '900', color: '#ea580c', fontSize: '11px', margin: '0 0 8px', textTransform: 'uppercase' }}>{data.organization}</p>
              <div style={{ fontSize: '9px', color: '#6b7280', lineHeight: '1.7' }}>
                {data.orgAddress && <p style={{ margin: '0 0 2px' }}>{data.orgAddress}</p>}
                {data.orgPhone && <p style={{ margin: '0 0 2px' }}>{data.orgPhone}</p>}
                {data.orgEmail && <p style={{ margin: 0 }}>{data.orgEmail}</p>}
              </div>
              {data.validUntil && <p style={{ fontSize: '9px', color: '#ea580c', fontWeight: '600', marginTop: '8px' }}>Valid: {data.validUntil}</p>}
              <p style={{ position: 'absolute', bottom: '10px', left: '14px', fontSize: '7px', color: '#d1d5db' }}>Return if found. Thank you!</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
