export interface OfferLetterData {
  candidateName: string;
  position: string;
  department: string;
  salary: string;
  joiningDate: string;
  companyName: string;
  companyAddress: string;
  companyPhone: string;
  companyEmail: string;
  hrName: string;
  hrTitle: string;
  letterDate: string;
  terms?: string;
  probationPeriod?: string;
  workHours?: string;
}

interface Props { data: OfferLetterData; isPro?: boolean; }

export function OfferLetterTemplate1({ data, isPro = false }: Props) {
  return (
    <div style={{ backgroundColor: '#fff', padding: '60px', maxWidth: '800px', margin: '0 auto', minHeight: '1056px', fontFamily: 'system-ui, sans-serif', position: 'relative' }}>
      {!isPro && <div style={{ position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%,-50%) rotate(-45deg)', fontSize: '48px', fontWeight: 'bold', color: 'rgba(128,128,128,0.10)', pointerEvents: 'none', whiteSpace: 'nowrap', zIndex: 9999 }}>PDFDecor Free</div>}
      <div style={{ borderBottom: '3px solid #2563eb', paddingBottom: '20px', marginBottom: '32px' }}>
        <h1 style={{ fontSize: '22px', fontWeight: 'bold', color: '#2563eb', margin: 0 }}>{data.companyName}</h1>
        <p style={{ color: '#6b7280', fontSize: '13px', margin: '4px 0 0' }}>{data.companyAddress} · {data.companyPhone} · {data.companyEmail}</p>
      </div>
      <p style={{ textAlign: 'right', fontSize: '13px', color: '#374151', marginBottom: '24px' }}>Date: {data.letterDate}</p>
      <p style={{ fontSize: '14px', marginBottom: '8px' }}>To,</p>
      <p style={{ fontWeight: 'bold', fontSize: '16px', marginBottom: '4px' }}>{data.candidateName}</p>
      <p style={{ fontSize: '14px', color: '#6b7280', marginBottom: '28px' }}>Dear {data.candidateName},</p>
      <h2 style={{ fontSize: '18px', fontWeight: 'bold', color: '#1f2937', textAlign: 'center', marginBottom: '20px', textTransform: 'uppercase', letterSpacing: '2px' }}>OFFER OF EMPLOYMENT</h2>
      <p style={{ fontSize: '14px', lineHeight: '1.8', marginBottom: '16px', color: '#374151' }}>
        We are pleased to offer you the position of <strong>{data.position}</strong> in the <strong>{data.department}</strong> department at <strong>{data.companyName}</strong>. Your joining date will be <strong>{data.joiningDate}</strong>.
      </p>
      <div style={{ background: '#eff6ff', borderLeft: '4px solid #2563eb', padding: '16px 20px', borderRadius: '4px', marginBottom: '20px' }}>
        <h3 style={{ margin: '0 0 12px', fontSize: '15px', color: '#1e40af' }}>Terms of Employment</h3>
        <table style={{ width: '100%', fontSize: '13px' }}>
          <tbody>
            {[['Position', data.position], ['Department', data.department], ['Joining Date', data.joiningDate], ['CTC / Salary', data.salary], data.probationPeriod ? ['Probation Period', data.probationPeriod] : null, data.workHours ? ['Working Hours', data.workHours] : null].filter(Boolean).map(([k, v]: any, i) => (
              <tr key={i}><td style={{ padding: '4px 0', color: '#6b7280', width: '160px' }}>{k}:</td><td style={{ padding: '4px 0', fontWeight: '600', color: '#1e40af' }}>{v}</td></tr>
            ))}
          </tbody>
        </table>
      </div>
      {data.terms && <p style={{ fontSize: '13px', color: '#374151', lineHeight: '1.7', marginBottom: '20px', whiteSpace: 'pre-line' }}>{data.terms}</p>}
      <p style={{ fontSize: '14px', color: '#374151', marginBottom: '40px', lineHeight: '1.7' }}>
        This offer is conditional upon successful completion of background verification. Please sign and return one copy of this letter to indicate your acceptance.
      </p>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: '48px' }}>
        <div>
          <div style={{ borderBottom: '1px solid #374151', width: '180px', marginBottom: '8px' }}></div>
          <p style={{ fontSize: '13px', fontWeight: 'bold', margin: 0 }}>{data.hrName}</p>
          <p style={{ fontSize: '12px', color: '#6b7280', margin: '2px 0' }}>{data.hrTitle}</p>
          <p style={{ fontSize: '12px', color: '#6b7280', margin: '2px 0' }}>{data.companyName}</p>
        </div>
        <div style={{ textAlign: 'right' }}>
          <div style={{ borderBottom: '1px solid #374151', width: '180px', marginBottom: '8px', marginLeft: 'auto' }}></div>
          <p style={{ fontSize: '13px', fontWeight: 'bold', margin: 0 }}>{data.candidateName}</p>
          <p style={{ fontSize: '12px', color: '#6b7280', margin: '2px 0' }}>Candidate Signature</p>
          <p style={{ fontSize: '12px', color: '#6b7280', margin: '2px 0' }}>Date: ___________</p>
        </div>
      </div>
      {!isPro && <p style={{ textAlign: 'center', fontSize: '11px', color: '#9ca3af', marginTop: '40px' }}>Generated by PDFDecor.in</p>}
    </div>
  );
}

export function OfferLetterTemplate2({ data, isPro = false }: Props) {
  return (
    <div style={{ backgroundColor: '#fff', padding: '50px', maxWidth: '800px', margin: '0 auto', minHeight: '1056px', fontFamily: 'Georgia, serif', position: 'relative' }}>
      {!isPro && <div style={{ position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%,-50%) rotate(-45deg)', fontSize: '48px', fontWeight: 'bold', color: 'rgba(128,128,128,0.10)', pointerEvents: 'none', whiteSpace: 'nowrap', zIndex: 9999 }}>PDFDecor Free</div>}
      <div style={{ textAlign: 'center', borderBottom: '1px solid #d1d5db', paddingBottom: '24px', marginBottom: '32px' }}>
        <h1 style={{ fontSize: '24px', fontWeight: 'bold', color: '#1f2937', margin: '0 0 4px', letterSpacing: '3px', textTransform: 'uppercase' }}>{data.companyName}</h1>
        <p style={{ color: '#6b7280', fontSize: '12px', margin: 0 }}>{data.companyAddress} | {data.companyPhone} | {data.companyEmail}</p>
      </div>
      <div style={{ textAlign: 'center', marginBottom: '32px' }}>
        <h2 style={{ fontSize: '20px', fontWeight: 'bold', color: '#374151', textTransform: 'uppercase', letterSpacing: '4px', margin: 0 }}>Letter of Offer</h2>
        <p style={{ color: '#6b7280', fontSize: '13px', marginTop: '8px' }}>{data.letterDate}</p>
      </div>
      <p style={{ fontSize: '14px', lineHeight: '1.8', marginBottom: '20px', color: '#374151' }}>
        Dear <strong>{data.candidateName}</strong>,
      </p>
      <p style={{ fontSize: '14px', lineHeight: '1.8', marginBottom: '20px', color: '#374151' }}>
        Following your recent interview, we are delighted to offer you the position of <strong>{data.position}</strong> in our <strong>{data.department}</strong> department. We believe your skills and experience will be a valuable addition to our team.
      </p>
      <div style={{ margin: '24px 0', padding: '20px', border: '1px solid #e5e7eb', borderRadius: '8px' }}>
        {[['Position Offered', data.position], ['Department', data.department], ['Date of Joining', data.joiningDate], ['Compensation (CTC)', data.salary], ...(data.probationPeriod ? [['Probation', data.probationPeriod]] : [])].map(([k, v], i) => (
          <div key={i} style={{ display: 'flex', padding: '6px 0', borderBottom: i < 4 ? '1px solid #f3f4f6' : 'none' }}>
            <span style={{ width: '200px', fontSize: '13px', color: '#6b7280' }}>{k}</span>
            <span style={{ fontSize: '13px', fontWeight: '600', color: '#1f2937' }}>{v}</span>
          </div>
        ))}
      </div>
      {data.terms && <p style={{ fontSize: '13px', color: '#374151', lineHeight: '1.8', fontStyle: 'italic', margin: '20px 0' }}>{data.terms}</p>}
      <p style={{ fontSize: '14px', color: '#374151', marginTop: '24px', marginBottom: '48px', lineHeight: '1.8' }}>
        We look forward to welcoming you to the {data.companyName} family. Please confirm your acceptance by signing below and returning this letter.
      </p>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '40px', marginTop: '40px' }}>
        <div>
          <div style={{ borderBottom: '1px solid #374151', marginBottom: '8px', height: '48px' }}></div>
          <p style={{ fontSize: '13px', fontWeight: 'bold', margin: 0 }}>{data.hrName}</p>
          <p style={{ fontSize: '12px', color: '#6b7280', margin: '2px 0' }}>{data.hrTitle} — {data.companyName}</p>
        </div>
        <div>
          <div style={{ borderBottom: '1px solid #374151', marginBottom: '8px', height: '48px' }}></div>
          <p style={{ fontSize: '13px', fontWeight: 'bold', margin: 0 }}>{data.candidateName}</p>
          <p style={{ fontSize: '12px', color: '#6b7280', margin: '2px 0' }}>Accepted | Date: _______</p>
        </div>
      </div>
      {!isPro && <p style={{ textAlign: 'center', fontSize: '11px', color: '#9ca3af', marginTop: '40px' }}>Generated by PDFDecor.in</p>}
    </div>
  );
}

export function OfferLetterTemplate3({ data, isPro = false }: Props) {
  return (
    <div style={{ backgroundColor: '#fff', padding: '0', maxWidth: '800px', margin: '0 auto', minHeight: '1056px', fontFamily: 'system-ui, sans-serif', position: 'relative' }}>
      {!isPro && <div style={{ position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%,-50%) rotate(-45deg)', fontSize: '48px', fontWeight: 'bold', color: 'rgba(128,128,128,0.10)', pointerEvents: 'none', whiteSpace: 'nowrap', zIndex: 9999 }}>PDFDecor Free</div>}
      <div style={{ background: 'linear-gradient(135deg, #6366f1, #4f46e5)', padding: '36px 48px', color: '#fff' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <h1 style={{ fontSize: '26px', fontWeight: '900', margin: 0 }}>{data.companyName}</h1>
            <p style={{ opacity: 0.8, fontSize: '12px', margin: '4px 0 0' }}>{data.companyAddress}</p>
          </div>
          <div style={{ textAlign: 'right', opacity: 0.85, fontSize: '12px' }}>
            <p style={{ margin: '2px 0' }}>{data.companyPhone}</p>
            <p style={{ margin: '2px 0' }}>{data.companyEmail}</p>
          </div>
        </div>
        <div style={{ marginTop: '24px', paddingTop: '20px', borderTop: '1px solid rgba(255,255,255,0.3)' }}>
          <h2 style={{ fontSize: '20px', fontWeight: 'bold', margin: 0, letterSpacing: '3px', textTransform: 'uppercase' }}>Offer of Employment</h2>
          <p style={{ opacity: 0.8, fontSize: '13px', margin: '6px 0 0' }}>{data.letterDate}</p>
        </div>
      </div>
      <div style={{ padding: '36px 48px' }}>
        <p style={{ fontSize: '14px', lineHeight: '1.8', marginBottom: '20px' }}>
          Dear <strong>{data.candidateName}</strong>,<br /><br />
          We are pleased to offer you the position of <strong style={{ color: '#4f46e5' }}>{data.position}</strong> in the <strong>{data.department}</strong> department at {data.companyName}, effective from <strong>{data.joiningDate}</strong>.
        </p>
        <div style={{ background: '#f0f0ff', borderRadius: '12px', padding: '20px', marginBottom: '24px' }}>
          <h3 style={{ color: '#4f46e5', margin: '0 0 14px', fontSize: '14px', textTransform: 'uppercase', letterSpacing: '1px' }}>Key Terms</h3>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px' }}>
            {[['Role', data.position], ['Department', data.department], ['Start Date', data.joiningDate], ['Annual CTC', data.salary]].map(([k, v], i) => (
              <div key={i} style={{ background: '#fff', borderRadius: '8px', padding: '10px 14px' }}>
                <p style={{ fontSize: '10px', color: '#6b7280', textTransform: 'uppercase', margin: '0 0 4px', letterSpacing: '1px' }}>{k}</p>
                <p style={{ fontWeight: 'bold', color: '#1f2937', margin: 0, fontSize: '14px' }}>{v}</p>
              </div>
            ))}
          </div>
        </div>
        {data.terms && <p style={{ fontSize: '13px', color: '#374151', lineHeight: '1.8', marginBottom: '20px' }}>{data.terms}</p>}
        <p style={{ fontSize: '13px', color: '#374151', lineHeight: '1.8', marginBottom: '40px' }}>Please sign and return this offer letter by the specified date to confirm your acceptance. We look forward to having you on the team!</p>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '40px' }}>
          <div>
            <div style={{ borderBottom: '2px solid #6366f1', paddingBottom: '4px', marginBottom: '8px', height: '44px' }}></div>
            <p style={{ fontWeight: 'bold', fontSize: '13px', margin: 0 }}>{data.hrName}</p>
            <p style={{ fontSize: '12px', color: '#6b7280', margin: '2px 0' }}>{data.hrTitle}</p>
          </div>
          <div>
            <div style={{ borderBottom: '2px solid #6366f1', paddingBottom: '4px', marginBottom: '8px', height: '44px' }}></div>
            <p style={{ fontWeight: 'bold', fontSize: '13px', margin: 0 }}>{data.candidateName}</p>
            <p style={{ fontSize: '12px', color: '#6b7280', margin: '2px 0' }}>Acceptance Date: _______</p>
          </div>
        </div>
      </div>
      {!isPro && <p style={{ textAlign: 'center', fontSize: '11px', color: '#9ca3af', paddingBottom: '20px' }}>Generated by PDFDecor.in</p>}
    </div>
  );
}

export function OfferLetterTemplate4({ data, isPro = false }: Props) {
  return (
    <div style={{ backgroundColor: '#fff', padding: '60px', maxWidth: '800px', margin: '0 auto', minHeight: '1056px', fontFamily: 'system-ui, sans-serif', borderLeft: '6px solid #0ea5e9', position: 'relative' }}>
      <div style={{ marginBottom: '32px' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', borderBottom: '1px solid #e0f2fe', paddingBottom: '20px' }}>
          <div>
            <h1 style={{ fontSize: '22px', fontWeight: '900', color: '#0369a1', margin: 0 }}>{data.companyName}</h1>
            <p style={{ fontSize: '12px', color: '#0284c7', margin: '4px 0 0' }}>{data.companyAddress}</p>
          </div>
          <div style={{ background: '#0ea5e9', color: '#fff', padding: '6px 16px', borderRadius: '20px', fontSize: '12px', fontWeight: 'bold' }}>OFFER LETTER</div>
        </div>
        <p style={{ fontSize: '13px', color: '#6b7280', margin: '12px 0 0' }}>{data.letterDate}</p>
      </div>
      <p style={{ fontSize: '15px', lineHeight: '1.8', marginBottom: '20px' }}>
        Dear <strong>{data.candidateName}</strong>,<br /><br />
        Congratulations! We are thrilled to extend this formal offer of employment for the role of <strong style={{ color: '#0369a1' }}>{data.position}</strong>.
      </p>
      <div style={{ margin: '20px 0', borderRadius: '8px', overflow: 'hidden', border: '1px solid #bae6fd' }}>
        {[['Position', data.position], ['Department', data.department], ['Date of Joining', data.joiningDate], ['CTC / Salary', data.salary], ...(data.probationPeriod ? [['Probation', data.probationPeriod]] : []), ...(data.workHours ? [['Work Hours', data.workHours]] : [])].map(([k, v], i) => (
          <div key={i} style={{ display: 'flex', padding: '10px 16px', backgroundColor: i % 2 === 0 ? '#f0f9ff' : '#fff', borderBottom: '1px solid #e0f2fe' }}>
            <span style={{ width: '180px', fontSize: '13px', color: '#6b7280' }}>{k}</span>
            <span style={{ fontSize: '13px', fontWeight: '600', color: '#0369a1' }}>{v}</span>
          </div>
        ))}
      </div>
      {data.terms && <p style={{ fontSize: '13px', color: '#374151', lineHeight: '1.8', margin: '20px 0' }}>{data.terms}</p>}
      <p style={{ fontSize: '13px', color: '#374151', lineHeight: '1.8', marginTop: '20px', marginBottom: '48px' }}>We're excited to have you join our team. Please sign and return this letter at your earliest convenience.</p>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '40px' }}>
        <div><div style={{ height: '48px', borderBottom: '2px solid #0ea5e9', marginBottom: '8px' }}></div>
          <p style={{ fontWeight: 'bold', fontSize: '13px', margin: 0 }}>{data.hrName}</p><p style={{ fontSize: '12px', color: '#6b7280', margin: '2px 0' }}>{data.hrTitle}</p></div>
        <div><div style={{ height: '48px', borderBottom: '2px solid #0ea5e9', marginBottom: '8px' }}></div>
          <p style={{ fontWeight: 'bold', fontSize: '13px', margin: 0 }}>{data.candidateName}</p><p style={{ fontSize: '12px', color: '#6b7280', margin: '2px 0' }}>Date: _______</p></div>
      </div>
    </div>
  );
}

export function OfferLetterTemplate5({ data, isPro = false }: Props) {
  return (
    <div style={{ backgroundColor: '#1a1a2e', color: '#e2e8f0', padding: '56px', maxWidth: '800px', margin: '0 auto', minHeight: '1056px', fontFamily: 'system-ui, sans-serif' }}>
      <div style={{ borderBottom: '1px solid #334155', paddingBottom: '24px', marginBottom: '32px', display: 'flex', justifyContent: 'space-between' }}>
        <div>
          <h1 style={{ fontSize: '24px', fontWeight: '900', color: '#a78bfa', margin: 0 }}>{data.companyName}</h1>
          <p style={{ fontSize: '11px', color: '#64748b', margin: '4px 0 0' }}>{data.companyAddress}</p>
        </div>
        <div style={{ border: '1px solid #a78bfa', color: '#a78bfa', padding: '4px 14px', borderRadius: '20px', fontSize: '12px', alignSelf: 'center', fontWeight: 'bold' }}>OFFER LETTER</div>
      </div>
      <p style={{ color: '#64748b', fontSize: '13px', marginBottom: '24px' }}>{data.letterDate}</p>
      <p style={{ fontSize: '15px', lineHeight: '1.8', marginBottom: '20px', color: '#cbd5e1' }}>
        Dear <strong style={{ color: '#e2e8f0' }}>{data.candidateName}</strong>,<br /><br />
        We're excited to offer you the role of <strong style={{ color: '#a78bfa' }}>{data.position}</strong> in our <strong>{data.department}</strong> department. Your journey with {data.companyName} begins on <strong>{data.joiningDate}</strong>.
      </p>
      <div style={{ background: '#16213e', borderRadius: '12px', padding: '20px', marginBottom: '24px', border: '1px solid #334155' }}>
        {[['Position', data.position], ['Department', data.department], ['Start Date', data.joiningDate], ['Compensation', data.salary]].map(([k, v], i) => (
          <div key={i} style={{ display: 'flex', justifyContent: 'space-between', padding: '8px 0', borderBottom: i < 3 ? '1px solid #334155' : 'none' }}>
            <span style={{ fontSize: '13px', color: '#64748b' }}>{k}</span>
            <span style={{ fontSize: '13px', fontWeight: '600', color: '#a78bfa' }}>{v}</span>
          </div>
        ))}
      </div>
      {data.terms && <p style={{ fontSize: '13px', color: '#94a3b8', lineHeight: '1.8', marginBottom: '20px' }}>{data.terms}</p>}
      <p style={{ fontSize: '13px', color: '#94a3b8', lineHeight: '1.8', marginBottom: '48px' }}>Please sign below to accept this offer. We look forward to your contribution.</p>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '40px' }}>
        <div><div style={{ height: '48px', borderBottom: '1px solid #a78bfa', marginBottom: '8px' }}></div>
          <p style={{ fontWeight: 'bold', fontSize: '13px', color: '#e2e8f0', margin: 0 }}>{data.hrName}</p><p style={{ fontSize: '12px', color: '#64748b', margin: '2px 0' }}>{data.hrTitle}</p></div>
        <div><div style={{ height: '48px', borderBottom: '1px solid #a78bfa', marginBottom: '8px' }}></div>
          <p style={{ fontWeight: 'bold', fontSize: '13px', color: '#e2e8f0', margin: 0 }}>{data.candidateName}</p><p style={{ fontSize: '12px', color: '#64748b', margin: '2px 0' }}>Date: _______</p></div>
      </div>
    </div>
  );
}
